/**
 * This class is generated by jOOQ
 */
package com.pan.springbootjooqtemplate.jooq;


import com.pan.springbootjooqtemplate.jooq.tables.Customer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demo.customer</code>.
     */
    public static final Customer CUSTOMER = com.pan.springbootjooqtemplate.jooq.tables.Customer.CUSTOMER;
}
